# Importing libraries 

In [235]:
import numpy as np
import pandas as pd

# import TRAIN dataset

In [236]:
dataset = pd.read_csv('train.csv')
X = dataset.iloc[:, [2, 3, 4, 5, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]].values
Y = dataset.iloc[:, -1].values

In [237]:
print(X)

[['Algiers' 19.4 31.9 ... 23.4 30.9 'Yes']
 ['Setif' 18.6 29.1 ... 20.6 28.0 'Yes']
 ['Sidi Bel Abbes' 12.2 29.7 ... 18.0 28.0 'No']
 ...
 ['Sidi Bel Abbes' 26.2 33.5 ... 29.1 30.2 'No']
 ['Skikda' 24.8 33.3 ... 25.5 32.7 'Yes']
 ['Setif' 24.7 33.3 ... 27.8 32.2 'Yes']]


In [238]:
print(Y)

['Yes' 'No' 'No' ... 'Yes' 'Yes' 'Yes']


In [239]:
Y = Y.reshape(-1,1)

In [240]:
print(Y)

[['Yes']
 ['No']
 ['No']
 ...
 ['Yes']
 ['Yes']
 ['Yes']]


# Dealing with invalid Data

In [241]:
from sklearn.impute import SimpleImputer
imputer_X = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer_Y = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X = imputer_X.fit_transform(X)
Y = imputer_Y.fit_transform(Y)

In [242]:
print(X)

[['Algiers' 19.4 31.9 ... 23.4 30.9 'Yes']
 ['Setif' 18.6 29.1 ... 20.6 28.0 'Yes']
 ['Sidi Bel Abbes' 12.2 29.7 ... 18.0 28.0 'No']
 ...
 ['Sidi Bel Abbes' 26.2 33.5 ... 29.1 30.2 'No']
 ['Skikda' 24.8 33.3 ... 25.5 32.7 'Yes']
 ['Setif' 24.7 33.3 ... 27.8 32.2 'Yes']]


# Encoding Dataset

In [243]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4])
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])
le4 = LabelEncoder()
X[:,7] = le4.fit_transform(X[:,7])
le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])
le6 = LabelEncoder()
Y[:,-1] = le6.fit_transform(Y[:,-1])
Y = le6.fit_transform(Y.flatten())

In [244]:
print(X)

[[0 19.4 31.9 ... 23.4 30.9 1]
 [7 18.6 29.1 ... 20.6 28.0 1]
 [8 12.2 29.7 ... 18.0 28.0 0]
 ...
 [8 26.2 33.5 ... 29.1 30.2 0]
 [9 24.8 33.3 ... 25.5 32.7 1]
 [7 24.7 33.3 ... 27.8 32.2 1]]


In [245]:
print(Y)

[1 0 0 ... 1 1 1]


# Feature Scaling

In [246]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [247]:
print(X)

[[-1.56597093  1.18231324  1.32687495 ...  1.05146763  1.43470175
   1.83895566]
 [ 0.86600837  1.05640186  0.9174323  ...  0.60882637  0.99969871
   1.83895566]
 [ 1.21343399  0.04911085  1.00517001 ...  0.19780234  0.99969871
  -0.5437869 ]
 ...
 [ 1.21343399  2.25255993  1.56084217 ...  1.95255877  1.32970102
  -0.5437869 ]
 [ 1.5608596   2.03221503  1.53159627 ...  1.38344858  1.70470363
   1.83895566]
 [ 0.86600837  2.0164761   1.53159627 ...  1.74704676  1.62970311
   1.83895566]]


# import TEST dataset

In [248]:
dataset_test = pd.read_csv('test.csv')
X_test = dataset_test.iloc[:, [2, 3, 4, 5, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]].values
Y_test = dataset_test.iloc[:, -1].values


In [249]:
print(X_test)
print(Y_test)

[['Batna' 11.4 33.5 ... 21.0 32.7 'No']
 ['Skikda' 15.5 39.6 ... 25.6 38.2 'No']
 ['Batna' 17.1 38.3 ... 29.2 37.0 'No']
 ...
 ['Sidi Bel Abbes' 25.2 31.7 ... 26.9 30.6 'Yes']
 ['Algiers' 26.3 30.9 ... 29.6 24.1 'Yes']
 ['Bejaia' 23.7 32.3 ... 29.2 31.4 'Yes']]
['No' 'No' 'No' ... 'Yes' 'Yes' 'Yes']


In [250]:
Y_test = Y_test.reshape(-1, 1)
print(Y_test)

[['No']
 ['No']
 ['No']
 ...
 ['Yes']
 ['Yes']
 ['Yes']]


# Dealing with invalid Data

In [251]:
from sklearn.impute import SimpleImputer
imputer_X = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer_Y = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X_test = imputer_X.fit_transform(X_test)
Y_test = imputer_Y.fit_transform(Y_test)

# Encoding Dataset

In [252]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X_test[:,0] = le1.fit_transform(X_test[:,0])
le2 = LabelEncoder()
X_test[:,4] = le2.fit_transform(X_test[:,4])
le3 = LabelEncoder()
X_test[:,6] = le3.fit_transform(X_test[:,6])
le4 = LabelEncoder()
X_test[:,7] = le4.fit_transform(X_test[:,7])
le5 = LabelEncoder()
X_test[:,-1] = le5.fit_transform(X_test[:,-1])
le6 = LabelEncoder()
Y_test[:,-1] = le6.fit_transform(Y_test[:,-1])
Y_test = le6.fit_transform(Y_test.flatten())

In [253]:
print(X_test)

[[2 11.4 33.5 ... 21.0 32.7 0]
 [9 15.5 39.6 ... 25.6 38.2 0]
 [2 17.1 38.3 ... 29.2 37.0 0]
 ...
 [8 25.2 31.7 ... 26.9 30.6 1]
 [0 26.3 30.9 ... 29.6 24.1 1]
 [3 23.7 32.3 ... 29.2 31.4 1]]


In [254]:
print(Y_test)

[0 0 0 ... 1 1 1]


In [255]:
Y_test = np.array(Y,dtype=float)
print(Y_test)

[1. 0. 0. ... 1. 1. 1.]


# Feature Scaling

In [256]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_test = sc.fit_transform(X_test)

In [257]:
print(X_test)

[[-0.85948847 -0.12536436  1.45502258 ...  0.61868499  1.60770983
  -0.54821094]
 [ 1.57609492  0.51974551  2.30602413 ...  1.32219276  2.39643096
  -0.54821094]
 [-0.85948847  0.7714957   2.12466314 ...  1.87276406  2.22434635
  -0.54821094]
 ...
 [ 1.22815443  2.04598106  1.20390737 ...  1.52101018  1.30656177
   1.82411537]
 [-1.55536943  2.21905932  1.09230061 ...  1.93393865  0.3744368
   1.82411537]
 [-0.51154798  1.80996525  1.28761244 ...  1.87276406  1.42128484
   1.82411537]]


# Training Model

In [258]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0)
classifier.fit(X, Y)

RandomForestClassifier(random_state=0)

In [259]:
print("Training Accuracy:", classifier.score(X, Y))

Training Accuracy: 1.0


In [260]:
y_pred = classifier.predict(X_test)


In [261]:
print(y_pred)

[0 0 0 ... 1 1 1]


In [262]:
new_df = pd.read_csv('test.csv')


In [263]:
df_test = pd.DataFrame()
df_test['Day'] = new_df['Day']  # Copy the 'Day' column
df_test['RainTomorrow'] = y_pred  # Add the predictions

# Convert 0/1 predictions to 'No'/'Yes'
df_test['RainTomorrow'] = df_test['RainTomorrow'].replace({0: 'No', 1: 'Yes'})

# Save the DataFrame to a CSV file
df_test.to_csv('rain_pred.csv', index=False)

# %%
print(df_test)


          Day RainTomorrow
0       76672           No
1       76673           No
2       76674           No
3       76675           No
4       76676           No
...       ...          ...
32312  108984          Yes
32313  108985          Yes
32314  108986          Yes
32315  108987          Yes
32316  108988          Yes

[32317 rows x 2 columns]
